### ISSUE TITLE
Peer review 2

### ISSUE THREAD

**Issue by TheSamsai** [gotonode/compress#7]
Repository cloned 21.2. at 18.24 o'clock

I was able to both build and run the tests on the project and the Huffman compression and decompression worked flawlessly against an executable binary. However, when I attempted to run the benchmarks and LZW compression, the program froze and threw segmentation faults in the JVM. This indicates that this is more likely a JVM bug and not an application logic bug. 

The code base is extremely well documented, with precise descriptions for each method and class along with sources to the algorithms. The code base is also well split up into multiple packages, which divide the various aspects of the application quite nicely and the classes follow the single responsibility principle.

The unit testing is fairly comprehensive on the file and method level, but the amount of test scenarios in the unit tests are quite limited. In addition, the unit tests follow a fairly generic naming scheme, which could lead to confusion about what a certain test does after the code base gets older. I would add more unit tests with different inputs and possibly scenarios where the application shouldn't work and compare the results against some kind of known values. This would have the benefit of being able to more clearly detect and pinpoint possible future regressions in the code.

The code quality overall is very good. Methods and variables are named clearly and due to the modular nature of the code and good comments there aren't unclear or complicated sections of code. 

One small problem I noticed was that sometimes functions that can fail have repeated exception handlers. A good example is the compress() function in Huffman.java. Here the code deals with a number of possible I/O exceptions using highly localized exception handlers. While handling errors locally is a good thing, in this case each of the exception handlers effectively does the same job and the algorithm cannot continue if any of the exceptions gets thrown. These sections of the code could be wrapped in a bigger "try { } catch { }" statement to reduce repetition and also to bring up line coverage of unit tests. An alternative approach would be to attempt to recover from each exception, but this would likely be difficult, or provide highly accurate error messages about where in the code the exception happened (to help with debugging or error reporting).

I'd say that the project is excellently done and what issues I found are quite minor or system-specific.

**Comment by gotonode** [comment]
Hello! Thank you for your peer review.

I do agree with the given points above. Testing has been neglected a little bit, and I'll work on improving their selection before the final deadline.

The LZW algorithm doesn't work on bigger files (over 0,5 MB). Or, it does work, but requires a lot of time and memory. From the user's perspective, it might seem that the app has crashed.

**Comment by gotonode** [comment]
Peer review has been taken into account and this issue is now closed. The received peer review was of excellent quality.
